### ISSUE TITLE
how does one get access to item magnet blacklist

### ISSUE THREAD

**Issue by DoomSquirter** [aaronhowser1/Genetics-Resequenced#12]
I have the gene and it's not picking up cobble

there's a option in client config to see items in blacklist in tooltips but cobble doesn't show up there

how are you supposed to access the blacklist and edit it?  don't see a key command for it

geneticsresequenced-1.21-1.1.1

**Comment by aaronhowser1** [comment]
Currently it uses item tags, it should be the tag `geneticsresequenced:magnet_blacklist`. [Cobblestone](https://github.com/aaronhowser1/Genetics-Resequenced/blob/NeoForge-1.21/src/generated/resources/data/geneticsresequenced/tags/item/magnet_blacklist.json) is the only item with that tag by default.

I might make it a per-player blacklist, if I can figure out a nice way to do that.

**Comment by DoomSquirter** [comment]
thanks!
