### ISSUE TITLE
[1.21] Potion of Cell Growth always crafts a Tuna potion

### ISSUE THREAD

**Issue by MuteTiefling** [aaronhowser1/Genetics-Resequenced#14]
This recipe always results in Cell Growth Entity Tuna. Making it impossible to set the type to something else. 
![image](https://github.com/user-attachments/assets/aba552c5-b897-4f53-a1dd-2056651e7bfd)

![image](https://github.com/user-attachments/assets/0f8154bc-a744-4469-b765-3b377092cd5a)

![image](https://github.com/user-attachments/assets/c0bd9e04-7564-43b5-81bc-82987afd870d)

**Comment by aaronhowser1** [comment]
![java_psBPYyxKyK](https://github.com/user-attachments/assets/e2c41f09-5d6c-4622-9482-0a7569cb64b2)

Can confirm that it's definitely not acting as it should

**Comment by aaronhowser1** [comment]
![idea64_Ez4jM1gjpB](https://github.com/user-attachments/assets/d2eed3c6-162c-4a2d-a821-304c796859cb)
![idea64_q5Er7GcStn](https://github.com/user-attachments/assets/6dfe7b95-55d4-43a4-bb1b-6c1d686c7433)
neither of these are even printing anything in the log 🤔

**Comment by aaronhowser1** [comment]
Aiight fixed for next update, ty for the report

**Comment by MuteTiefling** [comment]
awesome, thanks!
