### ISSUE TITLE
Seemingly unable to right click Ender Dragon for Organic Matter

### ISSUE THREAD

**Issue by MuteTiefling** [aaronhowser1/Genetics-Resequenced#15]
geneticsresequenced-1.21-1.1.9

**Describe the bug**
I've tried scraping the ender dragon while it was landed/perched in the middle, as well as in flight. Doesn't seem possible to do. 

**To Reproduce**
1. Go to the end
2. Right Click the dragon with a scraper

**Expected behavior**
Obtain Organic Matter

**Comment by aaronhowser1** [comment]
![image](https://github.com/user-attachments/assets/254e3cb2-4686-4c26-9f89-0e5628d1bb65)
Fixed for next update
