### ISSUE TITLE
Unable to enchant scrapers

### ISSUE THREAD

**Issue by MuteTiefling** [aaronhowser1/Genetics-Resequenced#16]
geneticsresequenced-1.21-1.1.9

**Describe the bug**
Scrapers show no viable enchants in an Enchanting Table. Can only enchant them via anvil. 

**To Reproduce**
1. Build a max enchanting table
2. Insert a scraper/lapis
3. No enchants show

**Expected behavior**
Delicate Touch should appear

**Screenshots**
![2024-08-04_20 23 36](https://github.com/user-attachments/assets/a4d1194e-a77b-42a1-9d1d-e0ba41ee2ea2)

**Additional context**
As a side note, the enchant also doesn't appear in the Bumblezone Crystal Flower which should allow crafting any enchant. Other modded enchants show up there without special modification. This makes me think there's potentially something with the enchant more than the tool, since the tool itself appears to have valid tags for allowing the enchant.

**Comment by MuteTiefling** [comment]
![2024-08-04_20 25 40](https://github.com/user-attachments/assets/a745b2a7-f749-4ec2-9510-079d433ab6a7)

**Comment by aaronhowser1** [comment]
![image](https://github.com/user-attachments/assets/382ed793-af0f-40ed-bc7d-fca7f317ed21)

This took me like an hour because someone told me that you don't need to put tags on enchantments and i looked everywhere besides there, and as it so turns out, you do in fact need tags on enchantments
