### ISSUE TITLE
[Bug] Matching Genes in Plasmid Infuser not giving correct amount of DNA points

### ISSUE THREAD

**Issue by MuteTiefling** [aaronhowser1/Genetics-Resequenced#18]
**Describe the bug**
When using matching DNA Helixes to create Plasmids the UI will say it gives +2 DNA points towards completion but they actually only give 1 point.

**Expected behavior**
Non Generic helixes should grant +2 progress on a plasmid

**Additional context**
[Add any other context about the problem here.](https://github.com/EnigmaticaModpacks/Enigmatica10/issues/74)

**Comment by aaronhowser1** [comment]
Is it just the first one that gives 1? I should probably make that one give nothing and just set the gene, actually

**Comment by aaronhowser1** [comment]
```kt
        if (DnaHelixItem.getGene(inputHelix) == ModGenes.BASIC.get()) {
            PlasmidItem.increaseAmount(outputPlasmid, 1)
            return
        } else {
            if (inputGene != plasmidGene) return
            PlasmidItem.increaseAmount(outputPlasmid, 1)
        }
```
yeah nope whoops, i'll fix that ty

**Comment by aaronhowser1** [comment]
```kt
        when (DnaHelixItem.getGene(inputHelix)) {
            ModGenes.BASIC.get() -> PlasmidItem.increaseDnaPoints(outputPlasmid, 1)
            plasmidGene -> PlasmidItem.increaseDnaPoints(outputPlasmid, 2)
            else -> return
        }
```
much nicer
