### ISSUE TITLE
[Bug] Hearts 2 Recipe

### ISSUE THREAD

**Issue by JimiRPG** [aaronhowser1/Genetics-Resequenced#23]
**Describe the bug**
There is no recipe for Hearts 2

In NEI (JEI) There is no recipe for Hearts 2. It does show some information but nothing on how to create the plasmid for hearts 2.

**Comment by aaronhowser1** [comment]
![image](https://github.com/user-attachments/assets/d4c564c6-912e-4a8b-85c0-eb81983a457f)

The recipe existed, it just didn't show in EMI. Fixed now, ty
