### ISSUE TITLE
[Bug] Crash when loading 1.3

### ISSUE THREAD

**Issue by MuteTiefling** [aaronhowser1/Genetics-Resequenced#29]
**Describe the bug**
Updated to 1.3 and am now getting a crash when starting the game

**Expected behavior**
no crash

**Screenshots**
n/a

**Additional context**
https://gist.github.com/MuteTiefling/f9ab9bb5d538032e8b2c2f9410cbd680

**Comment by aaronhowser1** [comment]
I forgot to test it on servers 🤦

**Comment by aaronhowser1** [comment]
Wait, when I launch a server I can connect to it fine. Hm...

**Comment by aaronhowser1** [comment]
Fixed in 1.3.1

**Comment by MuteTiefling** [comment]
Thanks!
