### ISSUE TITLE
[Bug] Can't place player in world due to Invalid Player Data on server

### ISSUE THREAD

**Issue by Darkfiend009** [aaronhowser1/Genetics-Resequenced#30]
**Describe the bug**
Updated existing server to Genetics: Resequenced to 1.3 and couldn't join with an "Invalid Player Data" error.

**To Reproduce**
1. Update server and client
2. Join Server
3. Receive Invalid Player Data error

**Expected behavior**
Connect to the server

**Additional context**
The debug.log shows some additional information stating that it could not place the player in the world. I've included it here:
debug.log: https://gist.github.com/Darkfiend009/156d421eba26165850c87d4e01b92e6b

**Comment by aaronhowser1** [comment]
Is that the entire debug.log? I can't find anything about that when searching `world` `player` or `world`.

Can you provide the client's log after it fails to join, as well?

**Comment by aaronhowser1** [comment]
I made a server on 1.2.3, gave myself a bunch of Genes, then updated to 1.3.0 and was able to join fine
