### ISSUE TITLE
[Bug] Gene prerequisites are incorrect

### ISSUE THREAD

**Issue by MuteTiefling** [aaronhowser1/Genetics-Resequenced#34]
**Describe the bug**
![image](https://github.com/user-attachments/assets/57cbf949-cfc6-482f-a005-83420b622943)

**Expected behavior**
should be teleport, jump boost, and no fall damage

**Additional context**
![image](https://github.com/user-attachments/assets/f14bb308-0aef-4ac4-8bbe-f21e455d7b3d)

**Comment by DoomSquirter** [comment]
more context

![image](https://github.com/user-attachments/assets/91534847-a410-4114-805c-420720133816)

my flight says flight/flight/flight but went off of book but I guess it's still thinking I need flight before flight yo dawg

**Comment by DoomSquirter** [comment]
to add to this
if I run 
/geneticsresequenced addGene fromId geneticsresequenced:flight DoomSquirter

I get the same error message.  it adds flight then fades cause of requirements

**Comment by aaronhowser1** [comment]
![image](https://github.com/user-attachments/assets/98367a64-4d25-42d0-a0bc-5514eecdf519)

The EMI info page was a very simple fix, I was literally just using the wrong variable when writing the component

**Comment by aaronhowser1** [comment]
![image](https://github.com/user-attachments/assets/e1164fd3-39e7-4869-b1bc-14b1a392bac5)

But I can't seem to replicate that second issue, hm. I did change required genes from being in the Gene constructor json to being its own datapack thing, maybe *that* fixed it?

**Comment by aaronhowser1** [comment]
If that issue persists after the upcoming update, please make a new issue for it
