### ISSUE TITLE
[Request] more Hearts > ugly UI 

### ISSUE THREAD

**Issue by flece** [aaronhowser1/Genetics-Resequenced#36]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my UI gets cluttered

**Describe the solution you'd like**
pls dont add more than the 10 hearts to the UI. Use Colors instead.

![image](https://github.com/user-attachments/assets/9cbd8c89-c564-4e97-80d0-03522b394725)

**Comment by aaronhowser1** [comment]
That's a vanilla thing. There's mods to make it use colors instead of multiple rows of hearts https://www.curseforge.com/minecraft/mc-mods/colorful-hearts
