### ISSUE TITLE
[Bug] Genetics blocks do not show up in Jade WAILA mod

### ISSUE THREAD

**Issue by theboo** [aaronhowser1/Genetics-Resequenced#37]
**Describe the bug**
[A clear and concise description of what the bug is.](https://gyazo.com/5ed91714f2eb63f293c230ac7f55ff35)

**To Reproduce**
1. install genetics, dependencies and jade
2. notice they dont show up as in the above gif

**Expected behavior**
they should show up!

It seems jade provides an error report!
[JadeErrorOutput.txt](https://github.com/user-attachments/files/17468850/JadeErrorOutput.txt)

**Comment by aaronhowser1** [comment]
Fixed 👍 ty for reporting
