### ISSUE TITLE
Client disconnects from LAN Servers

### ISSUE THREAD

**Issue by Mattabase** [aaronhowser1/Genetics-Resequenced#39]
**Describe the bug**
When connecting to a LAN server the client disconnects when receiving an unknown packet. 

**To Reproduce**
1. Open a LAN server with 1.5.0 of the mod installed
2. Join a LAN server with the mod installed
3. Open Console of the Server and/or Client

**Expected behavior**
Successful connection

**Additional context**
https://gist.github.com/Mattabase/30c52cc00e1f702a6ae881f1a6880aad

I have not had time to test this for dedicated servers yet, I will update the issue when that changes. 

*Sorry for the delay getting this issue made.

**Comment by Saereth** [comment]
Any word on this issue @aaronhowser1 ?

**Comment by aaronhowser1** [comment]
I've looked into it but I'm fully stumped. I don't think it happens on dedicated servers though, at least?

**Comment by AutumnalModding** [comment]
Aren't LAN worlds generally unsupported?

**Comment by aaronhowser1** [comment]
Unfortunately with Essential etc, I'm sure LAN is getting way more popular

**Comment by aaronhowser1** [comment]
![image](https://github.com/user-attachments/assets/faba34aa-6e19-48d1-87d8-883d3e89739d)

Can you see if it works with Modonomicon removed? That's what fixed it for me in dev just now

**Comment by Saereth** [comment]
yep it does, also saw the PR so yay :D

**Comment by aaronhowser1** [comment]
This *should* be fixed by just a Modonomicon update, I think. The PR was fixing datagen, and then the LAN part was a separate issue.
