### ISSUE TITLE
[Bug] Water breathing gene doesn't appear to be working

### ISSUE THREAD

**Issue by MuteTiefling** [aaronhowser1/Genetics-Resequenced#41]
**Describe the bug**
Water breathing gene doesn't actually let you breathe in water.

**To Reproduce**
1. apply gene
2. step into water
3. wait
4. drown

**Expected behavior**
The gene should be allowing you to breathe under water

**Additional context**
https://github.com/EnigmaticaModpacks/Enigmatica10/issues/207

**Comment by aaronhowser1** [comment]
Oh god, the bug causing this is causing a MILLION other bugs. Thanks for reporting so I can also squash all those lol

**Comment by aaronhowser1** [comment]
- Water Breathing
        - Flambé
        - Lay Egg
        - Meaty II
        - Green Death
        - Un-Undeath
        - Gray Death
        - White Death
        - Black Death 
        - Advancements that require Genes

Genes that weren't working
