### ISSUE TITLE
[Bug] Wither Hit causes wither on player when using the syringe

### ISSUE THREAD

**Issue by KingoftheHill52** [aaronhowser1/Genetics-Resequenced#42]
When you have the Wither Hit gene, using the syringe gives you wither for 4 seconds.

1. Inject syringe with Wither Hit gene
2. You get wither immediately
3. Use syringe to draw blood
4. you get wither again
5. This also happens when using the scraper on yourself

Wither Hit should not affect the player when damaging themselves

**Comment by aaronhowser1** [comment]
Fixed
