### ISSUE TITLE
[Memory Leak] ServerPlayer is leaked when a player dies

### ISSUE THREAD

**Issue by pietro-lopes** [aaronhowser1/Genetics-Resequenced#44]
**Describe the bug**
When a player dies, `InventoryListener.allListeners` holds an instance of dead player
**To Reproduce**
1. Login
2. `/kill @s`
3. Use IDE or do memory dump to check alive objects and you will see at least 2 `ServerPlayer`s

**Expected behavior**
Maybe use stopListening for dead player instance (grab from Clone event) and startListening for new player instance (_BE CAREFUL WITH CLONE EVENT, THE NEW PLAYER INSTANCE WILL CHANGE THE ID AFTER THE EVENT, SO IF YOU STORE IN A HASHSET BEFORE THIS CHANGE IT WILL NEVER HAVE A HASHCODE AS SAME AS IN A LATER MOMENT, USE `PlayerEvent.PlayerRespawnEvent` TO GRAB THE NEW PLAYER INSTANCE WITH THE FINAL ID/HASH_)

**Screenshots**

**Additional context**

**Comment by aaronhowser1** [comment]
Bit the bullet and figured out how ItemSubPredicates worked, and moved to those instead of having an InventoryListener
