### ISSUE TITLE
[Bug] Unable to craft Anti-Plasmid

### ISSUE THREAD

**Issue by MuteTiefling** [aaronhowser1/Genetics-Resequenced#47]
**Describe the bug**
Anti Plasmids cannot be attuned to a gene. When placed in a crafting table, there is no output available.

**Expected behavior**
Crafting a filled plasmid with an empty anti-plasmid should attune the anti-plasmid with the gene. 

**Screenshots**
See linked issue below

**Additional context**
https://github.com/EnigmaticaModpacks/Enigmatica10/issues/283

**Comment by aaronhowser1** [comment]
Fixed

**Comment by MuteTiefling** [comment]
Thanks!
