### ISSUE TITLE
[Bug] White Death recipe doesn't work

### ISSUE THREAD

**Issue by TNTRakete** [aaronhowser1/Genetics-Resequenced#48]
**Describe the bug**
Can't create White Death Helix in Incubator or advanced Incubator

**To Reproduce**
1. Make Bottle of Viral Agents
2. Get Dragon's Breath Helix
3. Put both in Incubator
4. Nothing will happen

**Expected behavior**
Incubator should produce Helix with White Death Gene

**Screenshots**
![image](https://github.com/user-attachments/assets/a2384d11-8452-4bbf-b4b4-bd9bfd49028f)

**Additional context**
Tested other Plagues via Modrinth so older version and they also don't work (Version 1.3.0)

**Comment by aaronhowser1** [comment]
Fixed
