### ISSUE TITLE
[Bug] Incubator cannot process any recipe

### ISSUE THREAD

**Issue by A-72** [aaronhowser1/Genetics-Resequenced#9]
![image](https://github.com/aaronhowser1/Genetics-Resequenced/assets/50094654/1a464cf4-cc32-49c8-b7c1-d9176ea973ea)

**Comment by aaronhowser1** [comment]
```java
    override fun hasRecipe(): Boolean {
        if (hasEnoughEnergy()) return false
``` 
lmao that was supposed to be inverted
